[package]
name = "supervisoRS"
version = "0.1.0"
edition = "2021"

[dependencies]
femtovg = { version = "0.9.2", features = ["glutin"] }
fs_extra = "1.3.0"
glutin = { version = "0.30", features = ["egl"], default-features = false }
glutin-winit = "0.3.0"
instant = "0.1.13"
platform-dirs = "0.3.0"
raw-window-handle = "0.5.0"
rustc-hash = "2.0.0"
shellexpand = "3.1.0"
sysinfo = "0.32.0"
winit = "0.28.7"
